CREATE TABLE IF NOT EXISTS roles (
    `id` VARCHAR(128) NOT NULL,
    `name` VARCHAR(100) UNIQUE NOT NULL,
    `description` VARCHAR(255),
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY uq_roles_name (`name`)
);